### ISSUE TITLE
link to repo is missing in pub.dev

### ISSUE THREAD

**Issue by guyluz11** [Levi-Lesches/opencv_ffi#15]
As you can see the links to the repo are missing 

![Screenshot_20231015_220159_Firefox](https://github.com/Levi-Lesches/opencv_ffi/assets/9304740/d145d19b-228f-4487-8231-c9b5954c4684)

**Comment by guyluz11** [comment]
It is a duplicate of #12, opening again because it got closed and the version didn't arrived to pub.dev

**Comment by Levi-Lesches** [comment]
Fixed in 1.1.0, published
