### ISSUE TITLE
Question - getting position of objects on the photo

### ISSUE THREAD

**Issue by PierreKasparian** [Levi-Lesches/opencv_ffi#26]
Hello,
Here is not really a bug but a question.
I was wondering if there was a method in this package that allows to get the position of the element in the picture.

In my case, i would like to get the position of every checkbox on a selected screenshot.

Is it possible ?

**Comment by Levi-Lesches** [comment]
Hi, thanks for the question. 

This package is mainly an interface to the OpenCV C++ SDK. I am not an expert on OpenCV's API, so I can't advise you here, but if you were to figure out how to accomplish this in C++, you can come back here and we can port it to Dart. For example, I am working on detecting [ArUco](https://docs.opencv.org/4.x/d5/dae/tutorial_aruco_detection.html) tags and needed to research the [`cv2::arcuo`](https://docs.opencv.org/4.x/d4/d17/namespacecv_1_1aruco.html) namespace before introducing it to this package, and now my video stream highlights any tags it finds.

Given that this is a question about OpenCV itself, I'm going to close this for now. But if you can find the OpenCV C++ code to accomplish what you want, please come back and re-open it so we can add it!
