### ISSUE TITLE
More points on pub.dev

### ISSUE THREAD

**Issue by guyluz11** [Levi-Lesches/opencv_ffi#3]
We can get more points on [pub.dev](https://pub.dev/packages/opencv_ffi) simply by running flutter format

![Screenshot_20230914_135928_Firefox](https://github.com/BinghamtonRover/OpenCV-FFI/assets/9304740/f3b31a33-3312-4057-b7c7-7b594f44ae95)

**Comment by Levi-Lesches** [comment]
Fixed in version `1.0.2`, thanks for the input!

![image](https://github.com/Levi-Lesches/opencv_ffi/assets/20747538/de9c416d-7e64-49c4-b8f9-15b8efc0d535)
