### ISSUE TITLE
[not a bug just a question] Can this library be created to verify facial similarity?

### ISSUE THREAD

**Issue by azkadev** [Levi-Lesches/opencv_ffi#5]
Sorry I'm very nub in the ml/ai/open cv field,

Can it be used for face similarity verification?

**Comment by Levi-Lesches** [comment]
Hi, thanks for your interest!

I'm not too well-versed on the ins and outs of OpenCV like AI and DNN, more the GUI and IO parts. If you can write some C++ or even rough Python code to do what you want, I can get that working in this library! All I need to know is which functions you want, what parameters they expect, and what they return. And any types or constructors as well.

**Comment by Levi-Lesches** [comment]
An update: We're trying to add ArUco tag detection, which means using some more modules (namely, the non-free ones). I'll look into how this affects our licensing but it does mean I'm open to adding more detection features in the future.

**Update**: I checked, ArUco is Apache 2.0 which permits distribution, so that's not a problem.

**Comment by guyluz11** [comment]
I'm also interested.
Planning on creating a dart native program that sends a live stream videon for a connected camera to a phone app whenever a movement get detected.
Please keep supporting dart native and open a new package in case there is a need to add flutter only functionality.

@Levi-Lesches what do you use this package for?

**Comment by Levi-Lesches** [comment]
@guyluz11
> Please keep supporting dart native and open a new package in case there is a need to add flutter only functionality.

Yep! This package supports native Dart. Just need to have the `opencv_ffi.dll` or `.so` files in your `PATH` or `LD_LIBRARY_PATH`, which can be done by running the `build.bat` or `build.sh` files. That support won't go away. In the near future, the Dart team will make this easier with the new [Native Assets](https://github.com/dart-lang/sdk/issues/50565) feature. Flutter support is under the [`opencv_camera`](https://github.com/Levi-Lesches/opencv_camera) package, which will implement the more familiar `package:camera` for desktop and other FFI environments. 

> what do you use this package for?

I'm a member of the [Binghamton University Rover Team](https://github.com/BinghamtonRover), where we use OpenCV in our [Video](https://github.com/BinghamtonRover/Video) program to control and stream our rover's cameras and stream to our PC app, the [Dashboard](https://github.com/BinghamtonRover/Dashboard) (also written in Flutter). 

The same request goes for you: If you need a specific OpenCV module or function, please open a new issue with the details and links to the official OpenCV docs. I'll close this issue as it's way too broad without specific details.

**Comment by guyluz11** [comment]
> @guyluz11
> 
> > Please keep supporting dart native and open a new package in case there is a need to add flutter only functionality.
> 
> Yep! This package supports native Dart. Just need to have the `opencv_ffi.dll` or `.so` files in your `PATH` or `LD_LIBRARY_PATH`, which can be done by running the `build.bat` or `build.sh` files. That support won't go away. In the near future, the Dart team will make this easier with the new [Native Assets](https://github.com/dart-lang/sdk/issues/50565) feature. Flutter support is under the [`opencv_camera`](https://github.com/Levi-Lesches/opencv_camera) package, which will implement the more familiar `package:camera` for desktop and other FFI environments.
> 
> > what do you use this package for?
> 
> I'm a member of the [Binghamton University Rover Team](https://github.com/BinghamtonRover), where we use OpenCV in our [Video](https://github.com/BinghamtonRover/Video) program to control and stream our rover's cameras and stream to our PC app, the [Dashboard](https://github.com/BinghamtonRover/Dashboard) (also written in Flutter).
> 
> The same request goes for you: If you need a specific OpenCV module or function, please open a new issue with the details and links to the official OpenCV docs. I'll close this issue as it's way too broad without specific details.

Sounds awesome, I think using it will do most of my work.
Currently I don't understand yet how to run it, opened issues about it in the repos (also several pr :) )
