### ISSUE TITLE
[not a issue] Built library files

### ISSUE THREAD

**Issue by bipinkrish** [Levi-Lesches/opencv_ffi#7]
Those who want to try this package/plugin without building OpenCV. I have built library files for Windows, Linux and Android check it out at https://github.com/bipinkrish/opencv-ffi-lib

**Comment by Levi-Lesches** [comment]
Thanks, but I'm not really looking to distribute or endorse closed-source binaries at the moment. Not that I have a specific reason to not trust _you_, but theoretically you could change those binaries at any time, which is a massive security risk. I'd much rather prefer linking to OpenCV and having a build script here.

I did spent a lot of time optimizing the build script to only build what this package needs so the build process takes 1-10 minutes from high-end PCs to Raspberry Pis. Besides, there is a bit of setup involved with adding the binaries to your PATH, so I figured it would be best to have that all in one package.

In the future, I am looking to use Dart's [Native Assets](https://github.com/dart-lang/sdk/issues/50565) feature. which will allow `dart pub get` to build OpenCV automatically.
